# Generated by Django 4.1.2 on 2022-10-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('item_completed', models.BooleanField()),
            ],
        ),
    ]
